# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9a6e18cf55d6e4982dbdbc728d9fcf6c5994a9e4c77bb00a91ed4d8139e2d3c33908dbd9bfee5600c3fb35de30d035aa4d5a546098e138034b41e2e46b6bdf9

test:
  secret_key_base: b2529f98a7dea9846c15d23464f066092b0b9d9b04d158532b4cf266def21bf6fc666faa8eab150b11905d47c8fded18f0638fd0a27fd717fbdba074ed0c39e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
